# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0.xci
# IP: The module: 'axi_uartlite_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0.xci
# IP: The module: 'axi_uartlite_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
