# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer.xci
# IP: The module: 'frame_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer.xci
# IP: The module: 'frame_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frame_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
