# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.cache/wt [current_project]
set_property parent.project_path C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/linear.coe
read_verilog -library xil_defaultlib {
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/Matrix_Generate_3x3_1Bit.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/Mini_LeNet.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/video_stream/axi2bram.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/cmos_capture_data.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/conv1.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/conv2.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/conv2_single.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/debounce/debounce_inputs.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/debounce/debouncer.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/dilation_detector.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/dividers/divider_2.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/dividers/divider_4.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/erosion_detector.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/video_stream/frame_read.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hdmi/hdmi_ctrl.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hdmi/hdmi_out.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hls_generated/img_filter.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hls_generated/img_filter_am_addhbi.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hls_generated/img_filter_lineBubkb.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hls_generated/img_filter_lineBucud.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hls_generated/img_filter_mac_muibs.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hls_generated/img_filter_mac_mujbC.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hls_generated/img_filter_mac_mukbM.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hls_generated/img_filter_mul_42g8j.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hls_generated/img_filter_mul_66fYi.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hls_generated/img_filter_mux_83eOg.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/imopen.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/key_debounce.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/linear.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/uart/master_axi.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/maxpool.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/video_stream/ov7670_init_regs.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/sccb/ov7670_read.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/predict_index.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/video_stream/processing.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/reshape.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/rgb2bin_process.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/rgb2ycbcr.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/sccb/sccb_ctrl.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/sccb/sccb_read.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/sccb/sccb_write.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/shift_register_2taps_1Bit.v
  C:/Users/nuha/Desktop/ece532_project/include_these_files/integration/verilog/state_machine.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/hdmi/tmds_encoder.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/uart/uart_ctrl.v
  C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/hdl/top.v
}
read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/ram/ram.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/ram/ram_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/axi_uartlite_0_1/axi_uartlite_0.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/ip/frame_buffer/frame_buffer_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/shift_reg_ram_1Bit/shift_reg_ram_1Bit.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/shift_reg_ram_1Bit/shift_reg_ram_1Bit_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/ram_data_in/ram_data_in.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/ram_data_in/ram_data_in_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/linebuffer/linebuffer.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/linebuffer/linebuffer_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/maxpool_linebuffer/maxpool_linebuffer.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/maxpool_linebuffer/maxpool_linebuffer_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_data_buffer/fifo_data_buffer.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_data_buffer/fifo_data_buffer.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_data_buffer/fifo_data_buffer_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_conv2_result/fifo_conv2_result.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_conv2_result/fifo_conv2_result.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_conv2_result/fifo_conv2_result_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/conv2_linebuffer/conv2_linebuffer.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/conv2_linebuffer/conv2_linebuffer_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_reshape/fifo_reshape.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_reshape/fifo_reshape.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_reshape/fifo_reshape_ooc.xdc]

read_ip -quiet C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/weights/weights.xci
set_property used_in_implementation false [get_files -all c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/weights/weights_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/constraints/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/src/constraints/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
