# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/weights/weights.xci
# IP: The module: 'weights' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/weights/weights_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weights'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/weights/weights.xci
# IP: The module: 'weights' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/weights/weights_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weights'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
