# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_data_buffer/fifo_data_buffer.xci
# IP: The module: 'fifo_data_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_data_buffer/fifo_data_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_data_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_data_buffer/fifo_data_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_data_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_data_buffer/fifo_data_buffer.xci
# IP: The module: 'fifo_data_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_data_buffer/fifo_data_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_data_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/fifo_data_buffer/fifo_data_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_data_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
