# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/shift_reg_ram_1Bit/shift_reg_ram_1Bit.xci
# IP: The module: 'shift_reg_ram_1Bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/shift_reg_ram_1Bit/shift_reg_ram_1Bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_reg_ram_1Bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/shift_reg_ram_1Bit/shift_reg_ram_1Bit.xci
# IP: The module: 'shift_reg_ram_1Bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/shift_reg_ram_1Bit/shift_reg_ram_1Bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_reg_ram_1Bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
