# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/ram_data_in/ram_data_in.xci
# IP: The module: 'ram_data_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/ram_data_in/ram_data_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_data_in'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/ram_data_in/ram_data_in.xci
# IP: The module: 'ram_data_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nuha/Desktop/ece532_project/camera-system-top/camera_system-master/proj/camera_system.srcs/sources_1/ip/ram_data_in/ram_data_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_data_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
